In [47]:
import pandas as pd
import numpy as np
import re
import os

df = pd.read_json('../Data/Serie_A_2023_games.json')

df_squad = pd.read_json('../Data/Serie_A_2023_squads.json').T

df_transposto = df.transpose()

df_transposto.head(20)

,Home,Away,Result,Players,Goals,Changes,Yellow cards,Red cards
1,Flamengo / RJ,Coritiba / PR,3 X 0,[[1Santos Aderbar Melo dos San ... T(g)P293428...,[11:00 1T6NRAyrton Lucas Dantas de Medeiros Fl...,[05:00 2TCoritiba/PR 30 - Robson dos Santos Fe...,[17:00 1T10Gabriel Barbosa Almeida Flamengo/RJ...,[]
2,Botafogo / RJ,São Paulo / SP,2 X 1,[[12Lucas Perri Lucas Estella Perri T(g)P33701...,[03:00 1T9NRFrancisco das Chagas Soares dos Sa...,[45:00 INTBotafogo/RJ 20 - Daniel Fortunato Bo...,"[03:00 2T9Jonathan Calleri São Paulo/SP, 08:00...",[]
3,Palmeiras / SP,Cuiabá / MT,2 X 1,[[21Weverton Weverton Pereira da Silva T(g)P16...,[04:00 1T9NREndrick Felipe Moreira de Sousa Pa...,[45:00 INTCuiabá Saf/MT 25 - Nicolas Quagliata...,[20:00 2T40Jhonatan dos Santos Rosa Palmeiras/...,[11:00 2T5Filipe Augusto Carvalho Souza - Cuia...
4,Corinthians / SP,Cruzeiro / MG,2 X 1,"[[12Cássio Cassio Ramos T(g)P166276, Corinthia...",[23:00 2T30NRMatheus de Araujo Andrade Corinth...,[45:00 INTCorinthians/SP 24 - Victor Danilo Ca...,[28:00 2T23Fagner Conserva Lemos Corinthians/S...,[]
5,Red Bull Bragantino / SP,Bahia / BA,2 X 1,[[40Lucão Lucas Alexandre Gald ... T(g)P523351...,"[44:00 1T9NREveraldo Stum Bahia/BA, 08:00 2T17...",[45:00 INTRed Bull Bragantino/SP 8 - Lucas Eva...,[21:00 1T29Francisco Vitor Silva Costa Bahia/B...,[]
6,Atlético Mineiro / MG,Vasco da Gama / RJ,1 X 2,[[22Everson Everson Felipe Marqu ... T(g)P1883...,[04:00 1T18NRAndrey Nascimento dos Santos Vasc...,[10:00 2TAtlético Mineiro/MG 25 - Mariano Ferr...,"[05:00 2T26Renzo Saravia Atlético Mineiro/MG, ...",[]
7,Grêmio / RS,Santos / SP,1 X 0,[[31Adriel Adriel Vasconcelos Ramos T(g)P55822...,[43:00 1T18NRJoao Pedro Maturano dos Santos Gr...,[45:00 INTSantos/SP 14 - Rodrigo Fernandez Ced...,"[05:00 2T19Douglas Moreira Fagundes Santos/SP,...",[41:00 2T10Yeferson Julio Soteldo Martinez - S...
8,Athletico Paranaense / PR,Goiás / GO,2 X 0,"[[1Bento Bento Matheus Krepski T(g)P446408, At...",[35:00 1T34NRPedro Henrique Ribeiro Goncalves ...,[45:00 INTAthletico Paranaense/PR 3 - Jose Iva...,"[21:00 1T4Sidimar Fernando Cigolini Goiás/GO, ...",[]
9,Fortaleza / CE,Internacional / RS,1 X 1,[[16Fernando M ... Fernando Miguel Kaufmann T(...,[08:00 2T11NRWanderson Maciel Sousa Campos Int...,[17:00 2TInternacional/RS 38 - Jean Dias da Co...,[+09:00 2T4Rodrigo Modesto da Silva Moledo Int...,[]
10,América / MG,Fluminense / RJ,0 X 3,[[1Matheus Matheus Fernando Cav ... T(g)P16892...,[06:00 2T14NRGerman Ezequiel Cano Fluminense/R...,[45:00 INTFluminense/RJ 99 - Leanderson da Sil...,"[40:00 1T4Vitor Mendes Alves Fluminense/RJ, +0...",[]
11,Fluminense / RJ,Athletico Paranaense / PR,2 X 0,"[[1Fabio Fabio Deivson Lopes ... T(g)P129292,...",[10:00 1T45NRVinicius Moreira de Lima Fluminen...,[45:00 INTAthletico Paranaense/PR 8 - Vitor Fr...,[33:00 2T11Marcos da Silva Franca Fluminense/R...,[]
12,Vasco da Gama / RJ,Palmeiras / SP,2 X 2,[[1Leo Jardim Leonardo Cesar Jardim T(g)P32363...,[28:00 1T9NRPedro Raul Garay da Silva Vasco da...,[16:00 2TPalmeiras/SP 18 - Jose Manuel Alberto...,"[15:00 1T8Jose Rafael Vivian Palmeiras/SP, 32:...",[]
13,São Paulo / SP,América / MG,3 X 0,"[[23Rafael Rafael Pires Monteiro T(g)P180213, ...",[20:00 1T10NRLuciano da Rocha Neves São Paulo/...,[13:00 2TSão Paulo/SP 20 - Gabriel Neves Perdo...,[15:00 1T29Pablo Gonçalves Maia Fortunato São ...,[]
14,Santos / SP,Atlético Mineiro / MG,0 X 0,[[34Joao Paulo Joao Paulo Silva Martins T(g)P3...,[],[12:00 2TSantos/SP 47 - Miguel Angel Terceros ...,[42:00 2T5Otavio Henrique Passos Santos Atléti...,[]
15,Goiás / GO,Corinthians / SP,3 X 1,"[[23Tadeu Tadeu Antonio Ferreira T(g)P308316, ...","[16:00 1T10NRRoger Krug Guedes Corinthians/SP,...",[45:00 INTCorinthians/SP 27 - Pedro Henrique S...,"[07:00 2T5Fausto Mariano Vera Corinthians/SP, ...",[]
16,Cruzeiro / MG,Grêmio / RS,1 X 0,[[1Rafael Cabral Rafael Cabral Barbosa T(g)P29...,[19:00 2T9NRBruno Rafael Rodrigues do Nascimen...,[13:00 2TCruzeiro Saf/MG 23 - Luiz Filipe da R...,"[03:00 2T9Luis Alberto Suarez Diaz Grêmio/RS, ...",[+7:00 2T6Lucas da Cruz Oliveira - Cruzeiro Sa...
17,Internacional / RS,Flamengo / RJ,2 X 1,"[[1Keiller Keiller da Silva Nunes T(g)P363886,...",[17:00 2T20NRGerson Santos da Silva Flamengo/R...,[20:00 2TInternacional/RS 27 - Mauricio Magalh...,[29:00 1T44Vitor Eduardo da Silva Matos Intern...,[]
18,Coritiba / PR,Fortaleza / CE,0 X 3,[[1Gabriel Gabriel Vasconcelos ... T(g)P31534...,[06:00 2T18NRSilvio Ezequiel Romero Fortaleza/...,[13:00 2TCoritiba/PR 7 - Andrey Ramos do Nasci...,[23:00 2T11Alef Mangueira Severino Pereira Cor...,[]
19,Bahia / BA,Botafogo / RJ,1 X 2,[[22Marcos Felipe Marcos Felipe de Fre ... T(g...,[28:00 1T37NRJose Antonio dos Santos Junior Bo...,[45:00 INTBotafogo/RJ 94 - Philipe Sampaio Aze...,"[+01:00 2T11Gabriel Teixeira Aragao Bahia/BA, ...",[]
20,Cuiabá / MT,Red Bull Bragantino / SP,1 X 1,[[1Walter Walter Leandro Capel ... T(g)P177853...,[22:00 2T98NRMateus da Silva Duarte Cuiabá Saf...,[45:00 INTRed Bull Bragantino/SP 7 - Eric dos ...,[18:00 1T16Henry David Mosquera Sanchez Red Bu...,[]

In [67]:
# Selecionar linhas onde 'Palmeiras / SP' aparece em 'Home' ou 'Away'
#df_transposto.loc[(df_transposto['Home'] == 'Palmeiras / SP') | (df_transposto['Away'] == 'Palmeiras / SP')]

In [105]:
df_squad.head(9)

,0,1,2,3,4,5,6,7,8
1,"{'Home': {'Squad': ['146379', '186825', '43089...","{'Home': {'Squad': ['146379', '186825', '43089...","{'Home': {'Squad': ['146379', '186825', '43089...","{'Home': {'Squad': ['146379', '186825', '43089...","{'Home': {'Squad': ['146379', '186825', '43089...","{'Home': {'Squad': ['146379', '186825', '43089...",NaN,NaN,NaN
2,"{'Home': {'Squad': ['135462', '167958', '14722...","{'Home': {'Squad': ['135462', '167958', '14722...","{'Home': {'Squad': ['135462', '167958', '14722...","{'Home': {'Squad': ['135462', '167958', '14722...","{'Home': {'Squad': ['135462', '167958', '14722...","{'Home': {'Squad': ['135462', '167958', '14722...",NaN,NaN,NaN
3,"{'Home': {'Squad': ['178854', '168387', '16224...","{'Home': {'Squad': ['178854', '168387', '16224...","{'Home': {'Squad': ['178854', '168387', '16224...","{'Home': {'Squad': ['178854', '168387', '16224...","{'Home': {'Squad': ['178854', '168387', '16224...","{'Home': {'Squad': ['178854', '168387', '16224...",NaN,NaN,NaN
4,"{'Home': {'Squad': ['155508', '183977', '17715...","{'Home': {'Squad': ['155508', '183977', '17715...","{'Home': {'Squad': ['155508', '183977', '17715...","{'Home': {'Squad': ['155508', '183977', '17715...","{'Home': {'Squad': ['155508', '183977', '17715...","{'Home': {'Squad': ['155508', '183977', '17715...",NaN,NaN,NaN
5,"{'Home': {'Squad': ['117336', '165065', '17241...","{'Home': {'Squad': ['117336', '165065', '17241...","{'Home': {'Squad': ['117336', '165065', '17241...","{'Home': {'Squad': ['117336', '165065', '17241...","{'Home': {'Squad': ['117336', '165065', '17241...",NaN,NaN,NaN,NaN
6,"{'Home': {'Squad': ['140911', '185679', '29741...","{'Home': {'Squad': ['140911', '185679', '29741...","{'Home': {'Squad': ['140911', '185679', '29741...","{'Home': {'Squad': ['140911', '185679', '29741...","{'Home': {'Squad': ['140911', '185679', '29741...","{'Home': {'Squad': ['140911', '185679', '29741...",NaN,NaN,NaN
7,"{'Home': {'Squad': ['305735', '186144', '17547...","{'Home': {'Squad': ['305735', '186144', '17547...","{'Home': {'Squad': ['305735', '186144', '17547...","{'Home': {'Squad': ['305735', '186144', '17547...","{'Home': {'Squad': ['305735', '186144', '17547...","{'Home': {'Squad': ['305735', '186144', '17547...",NaN,NaN,NaN
8,"{'Home': {'Squad': ['129292', '138932', '15728...","{'Home': {'Squad': ['129292', '138932', '15728...","{'Home': {'Squad': ['129292', '138932', '15728...","{'Home': {'Squad': ['129292', '138932', '15728...","{'Home': {'Squad': ['129292', '138932', '15728...",NaN,NaN,NaN,NaN
9,"{'Home': {'Squad': ['177770', '170272', '18955...","{'Home': {'Squad': ['177770', '170272', '18955...","{'Home': {'Squad': ['177770', '170272', '18955...","{'Home': {'Squad': ['177770', '170272', '18955...","{'Home': {'Squad': ['177770', '170272', '18955...","{'Home': {'Squad': ['177770', '170272', '18955...","{'Home': {'Squad': ['177770', '170272', '18955...",NaN,NaN

Teste inicial utilizando um jogo do brasileirão Série A 2014. Pegamos o primeiro jogo do Fluminense x Figueirense para criarmos a formatação das colunas e extração de informações da súmula.

In [48]:
players_teams = df_transposto.iloc[3, 3]
team_changes = df_transposto.iloc[3, 5]

start_players = df_squad.iloc[3,:]

# Criando DataFrame dos jogadores
new_df_players = pd.DataFrame(players_teams, columns=['player', 'team'])

def extract_id(player_string):
    # Ajuste para garantir que captura corretamente todas as variantes de ID
    match = re.search(r'T\(g\)?P(\d+)|RP(\d+)|TP(\d+)', player_string, re.IGNORECASE)
    if match:
        return next((m for m in match.groups() if m), None)
    return None

# Limpeza dos nomes dos jogadores
def clean_player_name(player):
    clean_name = re.sub(r'\s+T.*|\s+TP.*|\s+RP.*|\s+T(g).*', '', player)  # Remove texto após 'T' ou 'TP'
    return clean_name

new_df_players['player_id'] = new_df_players['player'].apply(extract_id)
new_df_players['player_name'] = new_df_players['player'].apply(clean_player_name)


def parse_team_changes(changes):
    pattern = re.compile(r'(\d{2}:\d{2}) (INT|\d+T)([\w\s]+/\w+) (\d+) - [^\d]+ (\d+) - [^\d]+')
    parsed_data = []
    for change in changes:

        match = pattern.search(change)
        if match:
            time, half, team, player_out_number, player_in_number = match.groups()
            team = team.strip()  # Limpeza para remover espaços extras
            parsed_data.append((time, half, team, player_out_number, player_in_number))
    return parsed_data


parsed_changes = parse_team_changes(team_changes)
print(team_changes)


new_df_players['Minutes Played'] = 90
new_df_players['Minute Entered'] = 0  # Todos os jogadores começam com entrada no minuto 0
new_df_players['Minute Exited'] = 90  # Todos os jogadores começam com saída no minuto 90

def verifica_substring(substring, string):
    partes = substring.split()
    return all(parte in string for parte in partes)


def tratar_excecoes_nomes_times(team):

    # Dicionário de exceções: chave é o nome parcial, valor é o nome completo
    excecoes = {
        "Atlético/PR": "Athletico Paranaense/PR",
        "Atlético/MG": "Atlético Mineiro/MG"
        # Adicione outras exceções aqui conforme necessário
    }
    
    # Verificar se o time está nas exceções e substituí-lo
    return excecoes.get(team, team)

for time, half, team, player_out_number, player_in_number in parsed_changes:

    team = tratar_excecoes_nomes_times(team)
    minute = int(time.split(':')[0])
    team = team.replace('/', ' / ')  # Formatando o nome do time corretamente
    
    if '2T' in half:
        minute_entered = 45 + minute
        minute_exited = 45 + minute
    else:
        minute_entered = minute
        minute_exited = minute

    team = re.sub(r' \b[sS][aA][fF]\b', '', team).strip()

    # Atualizar o jogador que entrou
    mask_in = (new_df_players['player_name'].apply(lambda x: re.match(r'^' + player_in_number + r'\D', x) is not None) & 
               new_df_players['team'].apply(lambda x: verifica_substring(team, x)))

    new_df_players.loc[mask_in, 'Minute Entered'] = minute_entered
    new_df_players.loc[mask_in, 'Minute Exited'] = 90  # O jogador que entra fica até o final do jogo

    # Atualizar o jogador que saiu
    mask_out = (new_df_players['player_name'].apply(lambda x: re.match(r'^' + player_out_number + r'\D', x) is not None) & 
                new_df_players['team'].apply(lambda x: verifica_substring(team, x)))
    new_df_players.loc[mask_out, 'Minute Exited'] = minute_exited

new_df_players['Minutes Played'] = new_df_players['Minute Exited'] - new_df_players['Minute Entered']


#setando Home ou Away
home_team = df_transposto.iloc[3, 0]
new_df_players
new_df_players['status'] = np.where(new_df_players['team'] == home_team, 'Home', 'Away')

new_df_players = new_df_players.drop(columns='player')
# Visualizando o novo DataFrame
new_df_players

['45:00 INTCorinthians/SP 24 - Victor Danilo Cantillo Jimenez 29 - Roni Medeiros de Moura', '40:00 1TCorinthians/SP 30 - Matheus de Araujo Andrade 20 - Giuliano Victor de Paula', '15:00 2TCruzeiro Saf/MG 10 - Maycon Vinicius Ferreira da ... 11 - Wesley Ribeiro Silva', '24:00 2TCorinthians/SP 28 - Adson Ferreira Soares 77 - Chrystian Amaral Barletta de...', '26:00 2TCruzeiro Saf/MG 23 - Luiz Filipe da Rosa Machado 17 - Ramiro Moschen Benetti', '30:00 2TCruzeiro Saf/MG 31 - Rafael Bilu Mudesto 7 - Mateus da Silva Vital Assump...']

,team,player_id,player_name,Minutes Played,Minute Entered,Minute Exited,status
0,Corinthians / SP,166276,12Cássio Cassio Ramos,90,0,90,Home
1,Corinthians / SP,178854,4Gil Carlos Gilberto do N ...,90,0,90,Home
2,Corinthians / SP,776923,5Fausto Fausto Mariano Vera,90,0,90,Home
3,Corinthians / SP,436395,9Yuri Alberto Yuri Alberto Monteir ...,90,0,90,Home
4,Corinthians / SP,389307,10Roger Guedes Roger Krug Guedes,90,0,90,Home
5,Corinthians / SP,178486,20Giuliano Giuliano Victor de Paula,50,40,90,Home
6,Corinthians / SP,502230,21Matheus Bidu Matheus Lima Beltrao ...,90,0,90,Home
7,Corinthians / SP,177050,23Fagner Fagner Conserva Lemos,90,0,90,Home
8,Corinthians / SP,648335,25Bruno Mendez Bruno Mendez Cittadini,90,0,90,Home
9,Corinthians / SP,387432,29Roni Roni Medeiros de Moura,45,45,90,Home
10,Corinthians / SP,546794,77Chrystian Chrystian Amaral Bar ...,21,69,90,Home
11,Corinthians / SP,None,22Carlos Carlos Miguel dos Sa ... R(g)P534596,90,0,90,Home
12,Corinthians / SP,162248,6Fabio Santos Fabio Santos Romeu,90,0,90,Home
13,Corinthians / SP,339242,7Maycon Maycon de Andrade Ba ...,90,0,90,Home
14,Corinthians / SP,507462,11Angel Romero Angel Rodrigo Romero ...,90,0,90,Home
15,Corinthians / SP,179382,15Paulinho Jose Paulo Bezerra M ...,90,0,90,Home
16,Corinthians / SP,691641,24Cantillo Victor Danilo Cantil ...,45,0,45,Home
17,Corinthians / SP,697315,27Pedrinho Pedro Henrique Silva ...,90,0,90,Home
18,Corinthians / SP,513472,28Adson Adson Ferreira Soares,69,0,69,Home
19,Corinthians / SP,545392,30Matheus Ar ... Matheus de Araujo Andrade,40,0,40,Home
20,Corinthians / SP,541574,31Balbuena Fabian Cornelio Balb ...,90,0,90,Home
21,Corinthians / SP,580808,34Murillo Murillo Santiago Cos ...,90,0,90,Home
22,Corinthians / SP,448892,37Eduardo Sa ... Eduardo Santos Queiroz,90,0,90,Home
23,Cruzeiro / MG,292253,1Rafael Cabral Rafael Cabral Barbosa,90,0,90,Away
24,Cruzeiro / MG,364054,3Marlon Marlon Rodrigues Xavier,90,0,90,Away
25,Cruzeiro / MG,292282,4Luciano Ca ... Luciano Castan da Silva,90,0,90,Away
26,Cruzeiro / MG,405246,7Mateus Mateus da Silva Vita ...,15,75,90,Away
27,Cruzeiro / MG,404399,9Bruno Rodr ... Bruno Rafael Rodrigu ...,90,0,90,Away
28,Cruzeiro / MG,517179,11Wesley Rib ... Wesley Ribeiro Silva,30,60,90,Away
29,Cruzeiro / MG,309438,12William William de Asevedo F ...,90,0,90,Away
30,Cruzeiro / MG,295418,17Ramiro Ramiro Moschen Benetti,19,71,90,Away
31,Cruzeiro / MG,185444,21Gilberto Gilberto Oliveira So ...,90,0,90,Away
32,Cruzeiro / MG,376786,25Richard Richard Candido Coelho,90,0,90,Away
33,Cruzeiro / MG,349619,26Lucas Oliv ... Lucas da Cruz Oliveira,90,0,90,Away
34,Cruzeiro / MG,None,98Anderson P ... Anderson Silva da Paixão R(g)...,90,0,90,Away
35,Cruzeiro / MG,532986,5Wallisson Wallisson Luiz Alves ...,90,0,90,Away
36,Cruzeiro / MG,383527,8Neto Antonio Francisco Mo ...,90,0,90,Away
37,Cruzeiro / MG,306616,10Nikao Maycon Vinicius Ferr ...,60,0,60,Away
38,Cruzeiro / MG,541008,16Kaiki Bruno Kaiki Bruno da Silva,90,0,90,Away
39,Cruzeiro / MG,376217,18Matheus Matheus Isaias dos Santos,90,0,90,Away
40,Cruzeiro / MG,568151,22Stênio Stenio Zanetti,90,0,90,Away
41,Cruzeiro / MG,383537,23Filipe Mac ... Luiz Filipe da Rosa ...,71,0,71,Away
42,Cruzeiro / MG,333318,27Neris Hueglo dos Santos Neris,90,0,90,Away
43,Cruzeiro / MG,387443,31Bilu Rafael Bilu Mudesto,75,0,75,Away
44,Cruzeiro / MG,460331,33Igor Marqu ... Igor Marques Pacienc ...,90,0,90,Away
45,Cruzeiro / MG,551333,48Daniel JR Daniel de Melo Arauj ...,90,0,90,Away

In [49]:
import unicodedata

def tratar_excecoes_nomes_times_2(team):
    # Dicionário de exceções: chave é o nome parcial, valor é o nome completo
    excecoes = {
        "Athletico Paranaense/PR": "Atlético/PR",
        "Atlético Mineiro/MG": "Atlético/MG"
        # Adicione outras exceções aqui conforme necessário
    }
    
    # Verificar se o time está nas exceções e substituí-lo
    return excecoes.get(team, team)

def remove_accents(text):
    # Normalize the text to NFKD form and remove accents
    return ''.join(c for c in unicodedata.normalize('NFKD', text) if not unicodedata.combining(c))


def parse_goals(goals, home_team):
    pattern = re.compile(r'(\+?\d+)(:00)? (\d+T)([^\s]+)\s+([^\d]+?)\s+(.*)')

    
    parsed_goals = []
    for goal in goals:

        match = pattern.search(goal)


        if match:
            if '+' in (match.group(1)):
                minute = 45
            else:
                minute = int(match.group(1))

            half = match.group(3)

            scorer_info = match.group(4)

            player_name = match.group(5).strip()

            time_casa = df_transposto.iloc[3, 0]
            time_visitante = df_transposto.iloc[3, 1]
            print(match.group(6))
            print(time_casa)


            time_casa = time_casa.replace(' / ', '/')
            time_visitante = time_visitante.replace(' / ', '/')

            time_casa_except = tratar_excecoes_nomes_times_2(time_casa)

            time_casa_normalized = remove_accents(time_casa)
            time_casa_except_normalized = remove_accents(time_casa_except)

            if time_casa in  match.group(6) or time_casa_except in match.group(6) or time_casa_normalized in match.group(6) or time_casa_except_normalized in match.group(6):
                team = time_casa
            else: 
                team = time_visitante




            team = tratar_excecoes_nomes_times(team)
            team = team.replace('/', ' / ')
            # Convertendo para minuto total do jogo
            if '2T' in half and minute != 45:  # Ajusta para o tempo total no caso do segundo tempo
                minute += 45
            
            # Verificar se é um gol contra (CT)
            if 'CT' in scorer_info:
                if team == home_team:
                    team_status = 'Away'
                else:
                    team_status = 'Home'
            else:

                if team == home_team:
                    team_status = 'Home'
                else:
                    team_status = 'Away'
            
            parsed_goals.append((minute, team_status))
    return parsed_goals

home_team = df_transposto.iloc[3, 0]
parsed_goals = parse_goals(df_transposto.iloc[3,4], home_team)

parsed_goals

Araujo Andrade Corinthians/SP
Corinthians / SP
Guedes Corinthians/SP
Corinthians / SP
Cruz Oliveira Cruzeiro Saf/MG
Corinthians / SP

[(68, 'Home'), (87, 'Home'), (45, 'Away')]

In [50]:

new_df_players['Goals For'] = 0

new_df_players['Goals Against'] = 0

for minute, team in parsed_goals:
    # Jogadores em campo no momento do gol
    mask = (new_df_players['Minute Entered'] <= minute) & (new_df_players['Minute Exited'] >= minute)
    # Incrementar gols a favor
    mask_for = mask & (new_df_players['status'] == team)
    new_df_players.loc[mask_for, 'Goals For'] += 1
    
    # Incrementar gols contra
    mask_against = mask & (new_df_players['status'] != team)
    new_df_players.loc[mask_against, 'Goals Against'] += 1

# Exibindo o DataFrame final para verificar os resultados
new_df_players

,team,player_id,player_name,Minutes Played,Minute Entered,Minute Exited,status,Goals For,Goals Against
0,Corinthians / SP,166276,12Cássio Cassio Ramos,90,0,90,Home,2,1
1,Corinthians / SP,178854,4Gil Carlos Gilberto do N ...,90,0,90,Home,2,1
2,Corinthians / SP,776923,5Fausto Fausto Mariano Vera,90,0,90,Home,2,1
3,Corinthians / SP,436395,9Yuri Alberto Yuri Alberto Monteir ...,90,0,90,Home,2,1
4,Corinthians / SP,389307,10Roger Guedes Roger Krug Guedes,90,0,90,Home,2,1
5,Corinthians / SP,178486,20Giuliano Giuliano Victor de Paula,50,40,90,Home,2,1
6,Corinthians / SP,502230,21Matheus Bidu Matheus Lima Beltrao ...,90,0,90,Home,2,1
7,Corinthians / SP,177050,23Fagner Fagner Conserva Lemos,90,0,90,Home,2,1
8,Corinthians / SP,648335,25Bruno Mendez Bruno Mendez Cittadini,90,0,90,Home,2,1
9,Corinthians / SP,387432,29Roni Roni Medeiros de Moura,45,45,90,Home,2,1
10,Corinthians / SP,546794,77Chrystian Chrystian Amaral Bar ...,21,69,90,Home,1,0
11,Corinthians / SP,None,22Carlos Carlos Miguel dos Sa ... R(g)P534596,90,0,90,Home,2,1
12,Corinthians / SP,162248,6Fabio Santos Fabio Santos Romeu,90,0,90,Home,2,1
13,Corinthians / SP,339242,7Maycon Maycon de Andrade Ba ...,90,0,90,Home,2,1
14,Corinthians / SP,507462,11Angel Romero Angel Rodrigo Romero ...,90,0,90,Home,2,1
15,Corinthians / SP,179382,15Paulinho Jose Paulo Bezerra M ...,90,0,90,Home,2,1
16,Corinthians / SP,691641,24Cantillo Victor Danilo Cantil ...,45,0,45,Home,0,1
17,Corinthians / SP,697315,27Pedrinho Pedro Henrique Silva ...,90,0,90,Home,2,1
18,Corinthians / SP,513472,28Adson Adson Ferreira Soares,69,0,69,Home,1,1
19,Corinthians / SP,545392,30Matheus Ar ... Matheus de Araujo Andrade,40,0,40,Home,0,0
20,Corinthians / SP,541574,31Balbuena Fabian Cornelio Balb ...,90,0,90,Home,2,1
21,Corinthians / SP,580808,34Murillo Murillo Santiago Cos ...,90,0,90,Home,2,1
22,Corinthians / SP,448892,37Eduardo Sa ... Eduardo Santos Queiroz,90,0,90,Home,2,1
23,Cruzeiro / MG,292253,1Rafael Cabral Rafael Cabral Barbosa,90,0,90,Away,1,2
24,Cruzeiro / MG,364054,3Marlon Marlon Rodrigues Xavier,90,0,90,Away,1,2
25,Cruzeiro / MG,292282,4Luciano Ca ... Luciano Castan da Silva,90,0,90,Away,1,2
26,Cruzeiro / MG,405246,7Mateus Mateus da Silva Vita ...,15,75,90,Away,0,1
27,Cruzeiro / MG,404399,9Bruno Rodr ... Bruno Rafael Rodrigu ...,90,0,90,Away,1,2
28,Cruzeiro / MG,517179,11Wesley Rib ... Wesley Ribeiro Silva,30,60,90,Away,0,2
29,Cruzeiro / MG,309438,12William William de Asevedo F ...,90,0,90,Away,1,2
30,Cruzeiro / MG,295418,17Ramiro Ramiro Moschen Benetti,19,71,90,Away,0,1
31,Cruzeiro / MG,185444,21Gilberto Gilberto Oliveira So ...,90,0,90,Away,1,2
32,Cruzeiro / MG,376786,25Richard Richard Candido Coelho,90,0,90,Away,1,2
33,Cruzeiro / MG,349619,26Lucas Oliv ... Lucas da Cruz Oliveira,90,0,90,Away,1,2
34,Cruzeiro / MG,None,98Anderson P ... Anderson Silva da Paixão R(g)...,90,0,90,Away,1,2
35,Cruzeiro / MG,532986,5Wallisson Wallisson Luiz Alves ...,90,0,90,Away,1,2
36,Cruzeiro / MG,383527,8Neto Antonio Francisco Mo ...,90,0,90,Away,1,2
37,Cruzeiro / MG,306616,10Nikao Maycon Vinicius Ferr ...,60,0,60,Away,1,0
38,Cruzeiro / MG,541008,16Kaiki Bruno Kaiki Bruno da Silva,90,0,90,Away,1,2
39,Cruzeiro / MG,376217,18Matheus Matheus Isaias dos Santos,90,0,90,Away,1,2
40,Cruzeiro / MG,568151,22Stênio Stenio Zanetti,90,0,90,Away,1,2
41,Cruzeiro / MG,383537,23Filipe Mac ... Luiz Filipe da Rosa ...,71,0,71,Away,1,1
42,Cruzeiro / MG,333318,27Neris Hueglo dos Santos Neris,90,0,90,Away,1,2
43,Cruzeiro / MG,387443,31Bilu Rafael Bilu Mudesto,75,0,75,Away,1,1
44,Cruzeiro / MG,460331,33Igor Marqu ... Igor Marques Pacienc ...,90,0,90,Away,1,2
45,Cruzeiro / MG,551333,48Daniel JR Daniel de Melo Arauj ...,90,0,90,Away,1,2

In [57]:

def collect_unique_ids(data_folder, file_names, years):
    unique_ids = set()

    def process_dataframe(df):
        for column in df.columns:
            for cell in df[column]:
                if isinstance(cell, dict):  
                    for key in ['Home', 'Away']:
                        team_info = cell.get(key, {})
                        # Adicionar os IDs do 'Squad'
                        squad_ids = team_info.get('Squad', [])
                        unique_ids.update(squad_ids)


    for file_name in file_names:
        for year in years:
            file_path = os.path.join(data_folder, f'{file_name}_{year}_squads.json')
            if os.path.exists(file_path):
                df = pd.read_json(file_path)
                df_ = df.iloc[:,3]
                df = pd.DataFrame(df_)
                process_dataframe(df)
            else:
                print(f'Arquivo não encontrado: {file_path}')

    return list(unique_ids)

data_folder = '../Data/'
file_names = ['Serie_A']
years = range(2023, 2024)

unique_player_ids = collect_unique_ids(data_folder, file_names, years)

print(f'Total de IDs únicos coletados: {len(unique_player_ids)}')

Total de IDs únicos coletados: 28

In [58]:

df_players_final = new_df_players[new_df_players['player_id'].isin(unique_player_ids)]
df_players_final

,team,player_id,player_name,Minutes Played,Minute Entered,Minute Exited,status,Goals For,Goals Against
0,Corinthians / SP,166276,12Cássio Cassio Ramos,90,0,90,Home,2,1
1,Corinthians / SP,178854,4Gil Carlos Gilberto do N ...,90,0,90,Home,2,1
2,Corinthians / SP,776923,5Fausto Fausto Mariano Vera,90,0,90,Home,2,1
3,Corinthians / SP,436395,9Yuri Alberto Yuri Alberto Monteir ...,90,0,90,Home,2,1
4,Corinthians / SP,389307,10Roger Guedes Roger Krug Guedes,90,0,90,Home,2,1
5,Corinthians / SP,178486,20Giuliano Giuliano Victor de Paula,50,40,90,Home,2,1
6,Corinthians / SP,502230,21Matheus Bidu Matheus Lima Beltrao ...,90,0,90,Home,2,1
7,Corinthians / SP,177050,23Fagner Fagner Conserva Lemos,90,0,90,Home,2,1
8,Corinthians / SP,648335,25Bruno Mendez Bruno Mendez Cittadini,90,0,90,Home,2,1
9,Corinthians / SP,387432,29Roni Roni Medeiros de Moura,45,45,90,Home,2,1
10,Corinthians / SP,546794,77Chrystian Chrystian Amaral Bar ...,21,69,90,Home,1,0
16,Corinthians / SP,691641,24Cantillo Victor Danilo Cantil ...,45,0,45,Home,0,1
18,Corinthians / SP,513472,28Adson Adson Ferreira Soares,69,0,69,Home,1,1
19,Corinthians / SP,545392,30Matheus Ar ... Matheus de Araujo Andrade,40,0,40,Home,0,0
23,Cruzeiro / MG,292253,1Rafael Cabral Rafael Cabral Barbosa,90,0,90,Away,1,2
24,Cruzeiro / MG,364054,3Marlon Marlon Rodrigues Xavier,90,0,90,Away,1,2
25,Cruzeiro / MG,292282,4Luciano Ca ... Luciano Castan da Silva,90,0,90,Away,1,2
26,Cruzeiro / MG,405246,7Mateus Mateus da Silva Vita ...,15,75,90,Away,0,1
27,Cruzeiro / MG,404399,9Bruno Rodr ... Bruno Rafael Rodrigu ...,90,0,90,Away,1,2
28,Cruzeiro / MG,517179,11Wesley Rib ... Wesley Ribeiro Silva,30,60,90,Away,0,2
29,Cruzeiro / MG,309438,12William William de Asevedo F ...,90,0,90,Away,1,2
30,Cruzeiro / MG,295418,17Ramiro Ramiro Moschen Benetti,19,71,90,Away,0,1
31,Cruzeiro / MG,185444,21Gilberto Gilberto Oliveira So ...,90,0,90,Away,1,2
32,Cruzeiro / MG,376786,25Richard Richard Candido Coelho,90,0,90,Away,1,2
33,Cruzeiro / MG,349619,26Lucas Oliv ... Lucas da Cruz Oliveira,90,0,90,Away,1,2
37,Cruzeiro / MG,306616,10Nikao Maycon Vinicius Ferr ...,60,0,60,Away,1,0
41,Cruzeiro / MG,383537,23Filipe Mac ... Luiz Filipe da Rosa ...,71,0,71,Away,1,1
43,Cruzeiro / MG,387443,31Bilu Rafael Bilu Mudesto,75,0,75,Away,1,1